Iter9
Dorrrke/shortener-url pull request #10
Opened 2023-10-01 15:47 UTC by Dorrrke

2023-10-04 15:54 UTC, kilchik requested changes

2023-10-04 15:54 UTC, kilchik commented on cmd/shortener/main.go
> +		URLServer.AddFilePath("D:/Git_repos/shortener-url/tmp/short-url-db.json")
Такие константы лучше не держать в коде

2023-10-04 15:54 UTC, kilchik commented on pkg/server/server.go
> +	matched, err := regexp.MatchString(`^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]`, modelURL.URLAddres)
Регулярки - это всегда медленно и сложночитаемо, тебе здесь достаточно воспользоваться функциями из пакета strings

2023-10-04 15:54 UTC, kilchik commented on pkg/server/server.go
> +			logger.Log.Debug("error encoding responce", zap.Error(err))
Если произошла ошибка при формировании ответа, сервер должен вернуть 500

2023-10-04 15:54 UTC, kilchik commented on tmp/short-url-db.json
> +{"short_url":"b21d5a2c","original_url":"https://practicum.yandex.ru/learn/go-advanced/courses/84f4d4db-15f7-4efd-9c53-1d7e1f27ba14/sprints/139167/topics/e62b3464-6a07-477d-b64e-ba792ee1358b/lessons/d
Не стоит держать хранилище в репозитории

2023-10-04 15:54 UTC, kilchik commented on pkg/server/server.go
> +		return err
Ошибки недостаточно прокидывать наверх - их нужно предварительно обернуть с помощью errors.Wrap(err, "encode last url") из пакета github.com/pkg/errors или fmt.Errorf("encode last url: %w", err) из стандартного fmt

2023-10-04 15:54 UTC, kilchik commented on pkg/server/server.go
> +	s.filePath = fileName
Почему бы не передать filePath в конструкторе (New)

2023-10-04 15:54 UTC, kilchik commented on pkg/server/server.go
> +		writeURL(s.filePath, restorURL{urlID, string(body)})
writeURL может вернуть ошибку, все ошибки должны явно обрабатываться

2023-10-04 15:54 UTC, kilchik commented on pkg/server/server.go
> +		writeURL(s.filePath, restorURL{urlID, modelURL.URLAddres})
writeURL может вернуть ошибку, все ошибки должны явно обрабатываться

2023-10-04 19:10 UTC, Dorrrke commented on pkg/server/server.go
> +	s.filePath = fileName
Решил так не делать, тк в мейне я сначала создаю объект URLserver через New, а потом уже только паршу флаги и тд. И решил не плодить дополнительных переменных в мейне

2023-10-07 09:02 UTC, kilchik approved these changes

2023-10-07 09:02 UTC, kilchik commented on pkg/server/server.go
> +	if strings.Contains(string(body), "http://") || strings.Contains(string(body), "https://") {
HasPrefix будет эффективнее, а главное - проверять, что подстрока является префиксом, а не просто встречается в рандомном месте

2023-10-07 09:02 UTC, kilchik commented on pkg/server/server.go
> +			logger.Log.Debug("cannot save URL in file", zap.Error(err))
Если произошла ошибка, лога недостаточно - пользователь должен узнать об ошибке

2023-10-07 09:02 UTC, kilchik commented on pkg/server/server.go
> +			logger.Log.Debug("cannot save URL in file", zap.Error(err))
Лога недостаточно

2023-10-08 20:22 UTC, merged