Iter13
Dorrrke/shortener-url pull request #14
Opened 2023-10-15 15:55 UTC by Dorrrke

2023-10-18 18:30 UTC, kilchik requested changes

2023-10-18 18:30 UTC, kilchik commented on cmd/shortener/main.go
> +		conn, err := pgx.Connect(context.Background(), DBaddr)
Тут 10 строк копипаста, копипаста быть не должно

2023-10-18 18:30 UTC, kilchik commented on cmd/shortener/main.go
> +			logger.Log.Error("Error wile init db driver: " + err.Error())
В этом случае приложение не должно стартовать вообще

2023-10-18 18:30 UTC, kilchik commented on pkg/server/gzipCompres.go
> +	if statusCode < 300 || statusCode == 409 {
Почему именно для этих кодов?

2023-10-18 18:30 UTC, kilchik commented on pkg/server/server.go
>  	if req.Method == http.MethodGet {
chi уже реализует эту проверку

2023-10-18 18:30 UTC, kilchik commented on pkg/server/server.go
> +					if err != nil {
Это очень большая вложенность условий, очень тяжело читается. Попробуй сократить минимум в 3 раза.
Например, почему бы не сделать
```
if !validationURL(string(body)) {
  http.Error(...
}

urlID := strings.Split...
```
И т д

2023-10-18 18:30 UTC, kilchik commented on pkg/server/server.go
> +				if pgerrcode.IsIntegrityConstraintViolation(pgErr.Code) {
Тут копипаст - копипаста быть не должно

2023-10-18 18:30 UTC, kilchik commented on pkg/server/server.go
> +	if s.storage.DB != nil {
Тут напрашивается полиморфизм: 
- необходимо выделить методы, одинаковые для всех видов хранилищ и реализовать из них интерфейс Storage
- в main конструировать конкретную реализацию в зависимости от конфигурации (структура DBStorage или MemStorage - у каждой из них один и тот же набор методов)
- при конструировании server передавать не конкретную реализацию (DBStorage или MemStorage), а интерфейс

Так удастся избавиться от этих ифов в каждой функции и развязать реализацию сервера и хранилища (сейчас server знает слишком много про внутренее устройство storage)

2023-10-19 20:10 UTC, Dorrrke commented on pkg/server/gzipCompres.go
> +	if statusCode < 300 || statusCode == 409 {
Коды ниже 300, это информационные статусы и статусы об успехе, а 409 статус конфликта, который обрабатывается программой

2023-10-21 20:08 UTC, kilchik approved these changes

2023-10-21 20:08 UTC, kilchik commented on pkg/models/JsonModels.go
> +package models
Файлы принята именовать используя snake_case

2023-10-21 21:08 UTC, merged