Iter18
Dorrrke/shortener-url pull request #19
Opened 2023-12-25 20:50 UTC by Dorrrke

2023-12-26 08:56 UTC, gonozov0 requested changes
Отличная работа 👍
Внес много улучшений по документации, а также написал бенчмарки
Оставил пару комментариев по коду
Так же подскажи плиз, удалось ли разобраться с pprof? Посмотреть визуально, какие части твоего кода дольше всего выполняются и занимают памяти.
Спрашиваю потому, что пообщавшись на 1:1 у многих не сложилось полное понимание, как он работает
https://app.pachca.com/chats?thread_id=2568500&sidebar_message=112734394

2023-12-26 08:56 UTC, gonozov0 commented on pkg/storage/URLstorage.go
> +	ClearTables(ctx context.Context) error
На мой взгляд странно в интерфейсе завязываться на уже реляционную модель с таблицами. Для MemStorage не будет никаких таблиц. Уже вижу, к сожалению, методы по созданию таблиц, видимо в предыдущие разы код ревьюил не я.

Мне кажется стоит назвать метод как минимум Clear.
А в целом очистки данных у нас в бизнес логики вроде не должно быть, эта логика нужна только для тестов, поэтому и расширять интерфейс кажется нет особого смысла.
Просто реализуем такой метод и имплементаций и вызываем в тестах

2023-12-26 08:56 UTC, gonozov0 commented on internal/config/configServer.go
> +// Структура конфига с информацией об адрессе сервера.
По гайдлайнам в go документация на метод, структуры и прочее должны начинаться с названия самого метода, структуры и т.д.

2023-12-26 08:56 UTC, gonozov0 commented on pkg/server/gzipCompres.go
> +// Hеализация метода Read.
опечатался

2023-12-28 21:27 UTC, Dorrrke commented on pkg/storage/URLstorage.go
> +	ClearTables(ctx context.Context) error
Понял, что вы имеете в виду, в будующем рефакторинге уберу расширение интерфейса

2023-12-28 21:28 UTC, Dorrrke commented on internal/config/configServer.go
> +// Структура конфига с информацией об адрессе сервера.
Исправил

2023-12-28 21:28 UTC, Dorrrke commented on pkg/server/gzipCompres.go
> +// Hеализация метода Read.
А ой

2023-12-29 11:01 UTC, gonozov0 approved these changes
Работа сдана 👍
Все критичные моменты поправлены

2024-01-04 22:17 UTC, merged